AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create an EC2 instance

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: EC2 Instance Type

  ImageIdParameter:
    Type: String
    Default: ami-059cdad1f35de63c0
    Description: Amazon Machine Image (AMI) IDs

  KeyNameParameter:
    Type: String
    Default: mstest-key
    Description: EC2 Key Pair Name

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: Ref InstanceTypeParameter
      ImageId: Ref ImageIdParameter
      KeyName: Ref KeyNameParameter
